name: simple_live_core
version: 1.0.4
description: '聚合直播核心库'
repository: https://github.com/xiaoyaocz/dart_simple_live
publish_to: 'none'
environment:
    sdk: '>=3.0.5 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    dio: ^5.9.0
    logger: ^2.6.1
    web_socket_channel: ^3.0.3
    html_unescape: ^2.0.0
    protobuf: ^4.2.0
    crypto: ^3.0.6
    brotli: ^0.6.0
    tars_flutter:
        git:
            url: https://github.com/dbjiasb/TarsFlutter.git
            branch: main
    fixnum: ^1.1.1
    flutter_qjs:
        git:
            url: https://github.com/wgh136/flutter_qjs.git
            branch: master
    dart_sm_new: ^0.1.9

dev_dependencies:
    lints: ^6.0.0
    test: ^1.26.3

flutter:
    assets:
        - assets/js/douyin-webmssdk.js
