name: simple_live_console
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
    sdk: '>=3.9.0 <4.0.0'
    flutter: 3.35.5

dependencies:
    simple_live_core:
        path: ../simple_live_core

dev_dependencies:
    flutter_lints: ^6.0.0
    flutter_test:
        sdk: flutter
